### ISSUE TITLE
Resharper runs all tests even If i selected to run only 1 

### ISSUE THREAD

**Issue by qbunia** [machine/machine.specifications.runner.resharper#10]
Hello,

I found a bug that wasnt present when I was using 8.0 version of Resharper using your extension( now Iam suing resharper 9.0 and newest version of your extension). The bug looks like this:
If i debug test2, before entering test2 breakpoint will be hit on the test1 first then it will go to test2.
If I debug test1, it will run test1 correct but then it will process to run other tests in this case: test2.

![resharper_bug](https://cloud.githubusercontent.com/assets/4216246/5896871/3d5f6ba2-a53d-11e4-80a0-3fb528e9a5b3.png)

**Comment by agross** [comment]
At least before @danielmarbach and friends took over mspec this was by design.

**Comment by qbunia** [comment]
Is it possible to make workaround do this or maybe I can ask some1 for feature request?

**Comment by agross** [comment]
The workaround is to delete one of the two breakpoints. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by qbunia** [comment]
It doesnt change anything because the code is still executed without my knowledge.

**Comment by agross** [comment]
As I said, this is by design. Your `It`s should only check system state or interactions, but not modify system state or cause new interactions to happen. As such, they should be fast and not change anything. So why exactly is it problematic for you to have them executed?

**Comment by qbunia** [comment]
I have integration tests that should be run in specified order.

**Comment by agross** [comment]
mspec does not guarantee ordered execution of either contexts (classes) or specifications (`It`s). The only this we guarantee is that `Establish`, `Because`, `It`s and `Cleanup` are executed in order. You need to rewrite your integration tests to be executable in any order.

Like I said, `It`s should only *observe*  system state or interaction, not actually *do*  anything.

**Comment by danielmarbach** [comment]
It still is by design
  
  
   On January 26, 2015 at 11:17 AM Alexander Groß <notifications@github.com> wrote:
   
   
   At least before @danielmarbach and friends took over mspec this was by design.
