### ISSUE TITLE
ReSharper 9 Integration With Visual Studio 2013 Update 4

### ISSUE THREAD

**Issue by sonalsatpute** [machine/machine.specifications.runner.resharper#11]
Team:

I am not sure how to Integrate MSpec test runner for *Reshaper 9* with Visual Studio 2013.

We have support for ReSharper (≥ 8.2 && < 8.3) (https://www.nuget.org/packages/Machine.Specifications.Runner.Resharper/).

I have download the source from (https://github.com/machine/machine.specifications.runner.resharper) and build it on my box. 

Please help me with where to find the documentation/help to register the Mspe Test Runner for ReShaper 9.

**Comment by agross** [comment]
Take a look at the ReSharper extension gallery directly in VS. You can install the runner from there. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by danielmarbach** [comment]
See http://www.planetgeek.ch/2014/07/08/machine-specifications-0-8-3-released/ and also http://www.planetgeek.ch/2014/12/29/machine-specifications-runner-resharper-1-0-0-released/

**Comment by sonalsatpute** [comment]
Awesome Alex !!! it was quick and worked for me ;)
