### ISSUE TITLE
Resharper 9.1

### ISSUE THREAD

**Issue by kevinkuebler** [machine/machine.specifications.runner.resharper#14]
I just installed R# 9.1 and am unable to find the MSpec runner in the R# extension gallery. I noticed this repo mentions that it supports 8.2 and 9.0. Is the package tied specifically to 9.0 such that it won't work with 9.1? (Actually, I see very few extensions available for 9.1 ... is R# really that sensitive to minor version changes for extensions?)

Is anybody able to run the MSpec runner in 9.1, and if so how do you do it?

**Comment by agross** [comment]
There is currently no runner and yes, ReSharper sometimes is very sensitive. I tried porting the 9.0 runner yesterday but that joy named NuGet failed to update the ReSharper SDK from 9.0 to 9.1.



Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by Gonzo102** [comment]
What version of VS are you using?




Thanks!
Kenneth S. Hines

**Comment by agross** [comment]
VS 2013 



Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by Gonzo102** [comment]
okay I am having an issue with the r# extension at the moment too.  Until I can repro it and get it fixed, I have an alternative if you’re interested.





Thanks!
Kenneth S. Hines

**Comment by agross** [comment]
An alternative to what?

Beste Grüße,

Alex
-- 
Alexander Groß
http://therightstuff.de/

**Comment by kevinkuebler** [comment]
Ah, forgot to mention that, I'm on VS 2013 also. I didn't realize that R# minor versions caused that much of an issue with extensions, but they obviously do as I only see a total of 6 extensions currently available in the whole gallery.

I'll use the command line runner for now, and hopefully you guys will be able to get it working soon. I'd love to help if I get some time ... but will have to crash course on both R# extensions and the MSpec runner codebase. :-)

**Comment by kevinkuebler** [comment]
I think the alternative Ken was referring to is the [MSpec adapter] (https://visualstudiogallery.msdn.microsoft.com/4abcb54b-53b5-4c44-877f-0397556c5c44) for the VS test runner. That option does actually work for me, so I will use that for now.

Thanks for all the work you guys do on MSpec!

**Comment by Gonzo102** [comment]
I have been using the MSpec Test Adapter for VS2012 and 2013.  until I can get my R# extension working again.

Thanks Ken.

**Comment by danielmarbach** [comment]
https://resharper-plugins.jetbrains.com/packages/Machine.Specifications.Runner.Resharper9/1.1.0-Beta0000

**Comment by kevinkuebler** [comment]
That was fast. :-)  I just installed it and so far, so good. Will let you know if I run into any issues. Thanks!

**Comment by mikeblakeuk** [comment]
+1 for R# 9.1, VS2013
