### ISSUE TITLE
Visual Studio 2010, Resharper 9.1 and recent version of runner not working

### ISSUE THREAD

**Issue by benfranklin79** [machine/machine.specifications.runner.resharper#17]
In resharper I add the extension and it says it's adding version 1.2.0-Unstable0001
Resharper details are:

```
JetBrains ReSharper Ultimate 2015.1 Build 102.0.20150408.145317
ReSharper 9.1.20150408.155143
```

I even restarted visual studio after installing the resharper extension. Visual studio details are:

```
Microsoft Visual Studio 2010
Version 10.0.40219.1 SP1Rel
Microsoft .NET Framework
Version 4.5.51209 SP1Rel
```

The tests I'm trying to run are actually from the following github repo:

https://github.com/Yegoroff/PlainElastic.Net

When I try to run any tests they come up as  inconclusive. Any ideas?

**Comment by SergVro** [comment]
I am having the same issue with Visual Studio 2013

````
JetBrains ReSharper Ultimate 2015.1 Build 102.0.20150408.145317
ReSharper 9.1.20150408.155143

Machine Specifications.Runner.Resharper9 build 1.1.0 on 2015-05-01 16:56:45Z.

Microsoft Visual Studio Professional 2013
Version 12.0.31101.00 Update 4
````

**Comment by Prosserc** [comment]
It would be great if you could support more recent versions of ReSharper (I am currently on 9.1.1), when I try to install `machine.specifications.runner.resharper` I get the following error:

![image](https://cloud.githubusercontent.com/assets/4390382/8846762/5761917c-3121-11e5-81ab-9e603ec98d6a.png)

**Comment by adamfisher** [comment]
I am curious what changes so much between versions that couldn't be achieved with reflection or something more dynamic?

**Comment by drauch** [comment]
@adamfisher: at least the R# SDK API you have to link against changes with each R# major release.
@Prosserc: The new runner (v 1.3.0) supports R# 10.0.2, the most current release.
