### ISSUE TITLE
ReSharper 9.2 support

### ISSUE THREAD

**Issue by ulrichb** [machine/machine.specifications.runner.resharper#19]
R# 9.2 was released yesterday and needs an update in the MSpec runner to support it.

**Comment by mikeblakeuk** [comment]
+1

**Comment by rlaci** [comment]
+1

**Comment by thrandre** [comment]
+1

**Comment by jaminto** [comment]
Are there manual steps to install for 9.2?  That would save a lot of headaches.

**Comment by thomaseyde** [comment]
Guess it's back to NUnit...

**Comment by jimmyheaddon** [comment]
+1

**Comment by richcorless** [comment]
+1

**Comment by chrisalexander** [comment]
+1

**Comment by patituccia** [comment]
+1

**Comment by gnschenker** [comment]
+1000!!!!

**Comment by justinSelf** [comment]
VoteCount++;

**Comment by qbunia** [comment]
+

**Comment by shaynevanasperen** [comment]
+1

**Comment by justinSelf** [comment]
Since the MSpec integration is more critical to my workflow than the new features in 9.2, I downgraded back to 9.1.3.

Download it here if you need to do the same: http://resharper-support.jetbrains.com/hc/en-us/articles/206104048-Where-can-I-download-an-old-previous-ReSharper-version-

**Comment by hennys** [comment]
As @danielmarbach has officially stepped down as the maintainer of this project, see http://www.planetgeek.ch/2015/04/28/bye-bye-machine-specifications/ for those of you that didn't know, I think that this project is more in need of your contribution and sense of ownership than another "+1" comment.

So if you are like me you are now looking at the source code to try and see what needs to be done or you are looking at options on how to migrate to another framework...

**Comment by danielmarbach** [comment]
If no breaking changes are present the process is simple:

Create new csproj for provider and runner which includes the same files
Reference latest wave of resharper sdk
Build, release done

**Comment by agross** [comment]
Develop contains a working 9.2 runner. I went through the process with the much appreciated help of @citizenmatt to fix breaking changes. The unstable runner worked for my test solution, but the [CI won't currently push it](https://teamcity.bbv.ch/viewLog.html?buildId=14117&buildTypeId=MachineSpecifications_MachineSpecificationsRunnerResharper&tab=buildLog).

**Comment by jimmyheaddon** [comment]
Good spot @hennys, that was 5 months ago and I hadn't noticed!  Disappointing news but it sounds fairly justified on @danielmarbach's part, a real shame.

@agross - Strange, it looks like it pushed - "[08:58:28][push] Your package was pushed.", but nothing in the Resharper Extension gallery.

**Comment by agross** [comment]
@jimmyheaddon It pushed the 9.1 runner, not the 9.2 runner.

**Comment by agross** [comment]
@jimmyheaddon (I guess, I didn't create that build config)

**Comment by agross** [comment]
The runner is available now: https://resharper-plugins.jetbrains.com/packages/Machine.Specifications.Runner.Resharper9.2

**Comment by agross** [comment]
Don't forget to restart VS after installing the extension.

**Comment by jimmyheaddon** [comment]
@agross Nice one, works a treat in VS2013

**Comment by citizenmatt** [comment]
@agross what I've been doing with 9.x plugins is pushing the e.g 9.2 version over the top of the 9.1 version, so they're all pushed to the same plugin ID. ReSharper will happily find the latest compatible version - 9.1 will see the last 9.1 version, 9.2 will see the new 9.2 version.

This does usually means that you stop supporting the 9.1 version, which reduces the maintenance cost on you lot, but if you leave a gap in the nuget package numbers, you can easily slot a fix to the 9.1 version in if you have to. We're encouraging people to upgrade ReSharper more quickly, and subscription licenses make this a whole lot more practical.

**Comment by agross** [comment]
@citizenmatt Thanks for the info!

**Comment by justinSelf** [comment]
Thanks for picking it up, @agross !

**Comment by codedrinker** [comment]
+1
