### ISSUE TITLE
NullReferenceException in Presentation.Element during test run

### ISSUE THREAD

**Issue by ulrichb** [machine/machine.specifications.runner.resharper#20]
I just tested _v1.2.0-Unstable0012_ in R# 9.2 (with /ReSharper.Internal). Although all tests ran and were reported as green, I got during the test run (of 1510 tests) about 90 `NullReferenceException`s with the stacktrace below. 

```
Message = “Object reference not set to an instance of an object.”
ExceptionPath = Root.InnerException
ClassName = System.NullReferenceException
HResult = COR_E_NULLREFERENCE=E_POINTER=80004003
Source = Machine.Specifications.ReSharper.Provider.9.2
StackTraceString = “
  at Machine.Specifications.ReSharperProvider.Presentation.Element.Equals(IUnitTestElement other)
     at JetBrains.ReSharper.UnitTestExplorer.Session.UnitTestSessionDescriptorBase.<OnTestResultsUpdated>b__3f(TreeModelNode node)
     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
     at JetBrains.ReSharper.UnitTestExplorer.Session.UnitTestSessionDescriptorBase.OnTestResultsUpdated(IEnumerable`1 nodesToUpdate)
     at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
”
```

PS: Also, it seems that the runtime performance degraded significantly: 2:40 for my test suite vs. 1:30 with MSpec 1.1.0 and R# 9.1.3 (same machine; same VS version; both with /ReSharper.Internal).

**Comment by ulrichb** [comment]
I further analyzed this bug with debug assemblies of the MSpec runner and saw that the null-deref happens in [line 155 of Element.cs](https://github.com/machine/machine.specifications.runner.resharper/blob/e53ba4d5873830f9f89fe3c60538c06efcff2c98/Machine.Specifications.ReSharper.Provider.9.1/Presentation/Element.cs#L155). So maybe we just need a null-check for `other`.

@citizenmatt: Is it expected that `UnitTestSessionDescriptorBase.OnTestResultsUpdated()` calls `unitTestElement.Equals(ActiveElement.Value)` with a null `ActiveElement.Value`? Or is this just a symptom of another issue?

I also tested adding a null-check (see #22). This fixed the exceptions in my test solution. (Unfortunately the execution time of the tests didn't improve.)

**Comment by citizenmatt** [comment]
Yes, I think it's expected that `OnTestResultsUpdated` can call `unitTestElement.Equals` with a `null` value. The active element is updated when "track elements" is enabled, and when it's not, I think the active element value is `null`. So, your element's `Equals` methods should expect a `null`. It's generally a good practice to check for being passed `null` in `Equals` - you can't control what you'll get called with, and it's perfectly viable for someone to try and compare the current instance with `null`.

**Comment by ulrichb** [comment]
Just pushed _1.2.0-Unstable0016_ which contains the fix.

Note that the mentioned performance degradation was due to [RSRP-447486](https://youtrack.jetbrains.com/issue/RSRP-447486) (introduced with R# 9.2). The tests were executed in x64 compared to x86 in R# 9.1. After changing the "Platform" selection in the "Test Session" window to x86 the tests ran even a bit faster than with 9.1 :)
