### ISSUE TITLE
Resharper 10 doesn't show failed test stack trace

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#25]
The output window of Unit Test Sessions is always empty.

see machine/machine.specifications#285

**Comment by bluerobotch** [comment]
I can reproduce the same behavior with NUnit and ReSharper10. It looks like a ReSharper bug. It happens when you add a test to a new test session and then run the test by selecting all tests at assembly or solution level:
![image](https://cloud.githubusercontent.com/assets/3074874/10998423/50127f54-8495-11e5-9807-d3062c2098eb.png)
![image](https://cloud.githubusercontent.com/assets/3074874/10998451/7c60f2ca-8495-11e5-9825-702ba4c263d8.png)

@SlyNet Try to close the unit test session and create a new one.

**Comment by citizenmatt** [comment]
Yep. It's a ReSharper bug. It's been fixed, and will be released in a hot fix, probably next week. In the meantime, there's a (workaround in this bug report](https://youtrack.jetbrains.com/issue/RSRP-450266#comment=27-1189192).
