### ISSUE TITLE
Support for ReSharper 10.0.2

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#26]
Add support for ReSharper 10.0.2.

As far as i've seen the following breaking change has to be fixed:

The `UnitTestElementState.Valid` and `UnitTestElementState.Pending` do not exist anymore.

**Comment by citizenmatt** [comment]
Uh-oh. There should be no breaking changes in the ReSharper API for a maintenance release. These values need to still exist. I'll follow up internally.

**Comment by citizenmatt** [comment]
Just checked, they've been removed by mistake. The API is changing for the next release (10.1), but they shouldn't have been removed yet. They'll be reinstated for the next EAP build, so unfortunately, you should consider EAP3 broken. Apologies. 

Please don't update your code - it will break anyone on 10.0 RTM or 10.0.1!

(The state needs to be removed from the element, as the element is intended to be a value object, with multiple instances being considered equal if the properties are equal. Having a mutable state field doesn't really work with that)

**Comment by bluerobotch** [comment]
@citizenmatt thanks for checking that. I will close the issue.
