### ISSUE TITLE
MissingMethodException: "Cannot create an abstract class."

### ISSUE THREAD

**Issue by Cephei** [machine/machine.specifications.runner.resharper#27]
Whenever I try to run my tests with Resharper test runner I get this exception - stemming from System.Activator.CreateInstance().

My tests run well from NCunch's MSpec runner.  Any idea what may be causing this?  Thanks!

**Comment by bluerobotch** [comment]
Which version of ReSharper and MSpec ReSharper runner are you using?
Do you have a stack trace for the exception?

**Comment by Cephei** [comment]
<img width="765" alt="screen shot 2016-02-01 at 11 34 36 am" src="https://cloud.githubusercontent.com/assets/1054639/12708891/f5feb71c-c8d7-11e5-983c-e4f2a093522e.png">

**Comment by Cephei** [comment]
I fixed the issue by removing all `abstract` keywords from my test classes.  Issue stems from https://github.com/machine/machine.specifications/blob/569a8b1c22fc8900444119b7084ef597006940f1/Source/Machine.Specifications/Explorers/AssemblyExplorer.cs

**Comment by bluerobotch** [comment]
@Cephei thanks.
