### ISSUE TITLE
Support for ReSharper 10.1

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#28]
Add support for ReSharper 10.1

**Comment by bluerobotch** [comment]
An unstable plugin is now up to the resharper plugin gallery. 

We still have to bugs open with resharper: 

The first one considering performance: https://youtrack.jetbrains.com/issue/RSRP-455504
The other one considering behavior specification elements: https://youtrack.jetbrains.com/issue/RSRP-455506

**Comment by Schaeri** [comment]
Updated to 2016.1. Performance is better than in EAP. But bugs are still open.
