### ISSUE TITLE
When selecting a folder to run tests all tests in the assembly are run

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#29]
When selecting a folder in Visual Studio, and then choosing "Run Unit Tests" from the context menu, all tests in the directory are appended to the test session. But all tests from the assembly are run.

The progress bar on top of the test session does indicate that.

**Comment by Schaeri** [comment]
Seems to be an issue in reshaper. xunit has the same problem. Should be fixed in EAP 10.1. Need to be verifyed.

**Comment by Schaeri** [comment]
Yes it is fixed. Tested with R# 10.1 EAP 5.

**Comment by Schaeri** [comment]
Updated to 2016.1. Bug is fixed.
