### ISSUE TITLE
When selecting a folder to run tests sometimes the tests do not get appended to the session

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#30]
When selecting a folder to run tests sometimes the tests do not get appended to the session. May be when there is the same namespace in multiple test assemblies.

**Comment by Schaeri** [comment]
Seams to be related to #29 and may be fixed in re sharper 10.1 EAP1. To be verified.

**Comment by Schaeri** [comment]
Yes it is fixed in EAP. Tested with R# 10.1 EAP 5.

**Comment by Schaeri** [comment]
Fixed in 2016.1.
