### ISSUE TITLE
Removed failing behavior -> rerun tests -> root node still red

### ISSUE THREAD

**Issue by drauch** [machine/machine.specifications.runner.resharper#32]
If you have a test with a failing behavior, the corresponding It nodes are red, the behavior node is red and of course all parent nodes are red as well.

If you decide to remove a failing It, the view should update. This update should happen at least when rerunning the whole root node. Unfortunately, at the moment, the root node is left "red", even though all sub nodes are now green.

I've found no other workaround than closing the whole R# test session and creating a new one. Looks like a bug in the R# MSpec extension to me, as the NUnit runner does not suffer from the same problems.

**Comment by bluerobotch** [comment]
I think this is partially related to #33 as changes to behaviors are not properly reflected.

**Comment by drauch** [comment]
Sounds very likely.

**Comment by ivanz** [comment]
@robertcoltheart Wondering if this is fixed by your recent changes?

**Comment by robertcoltheart** [comment]
Yep, it appears fixed to me.
