### ISSUE TITLE
Changes to behaviors cause wrong visualization and execution

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#33]
The recreation of unit test elements is only triggered when a file containing a specification context is modified. Behavior specification elements are usually defined in another file than the specification context that is using it. As soon as you remove an it from a behavior, the unit test element tree hold by resharper gets out of sync, causing strange behaviors like wrong visualization in the unit test sessions explorer and wrong execution.

As of ReSharper 10.1 we had to adjust the UnitTestElementDisposition beeing created for behavior sepcification elements because the location for the disposition has to match the file being processed.

But the BehaviorSpecificationElement still points to the field defined in the behavior class.

**Comment by Schaeri** [comment]
We should handle behaviors like xunit handles test methods in abstract base classes.

**Comment by ivanz** [comment]
@robertcoltheart Wondering if this is fixed by your recent changes?

**Comment by robertcoltheart** [comment]
Nope, this still looks like an issue. For this, the behavior needs to be in a different file and I can see the issue being replicated. Will take a look at this later.

**Comment by robertcoltheart** [comment]
Should be fixed, take a look.
