### ISSUE TITLE
Ruby gem for NuGet client is outdated

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#34]
The ruby gem for the nuget client https://rubygems.org/gems/nuget that is used for package restore and packaging is at version 2.8 and the latest version is 3.3 https://dist.nuget.org/index.html

The gem should either be updated or the nuget client should be checked into the github repo.

**Comment by ivanz** [comment]
Closing as Ruby is no longer used for building.
