### ISSUE TITLE
Behaviors (in different file as spec) are not displayed at all or state is moved back to "unknown"

### ISSUE THREAD

**Issue by drauch** [machine/machine.specifications.runner.resharper#35]
Behaviors which are in a different file than the original spec are executed, however, the state is immediately reset back to "unknown" (question mark):

![image](https://cloud.githubusercontent.com/assets/1516470/13955898/d1d9db32-f046-11e5-9d8e-8408ec016884.png)

If the behavior is in a different file AND in a base class, we SOMETIMES have an even more severe bug -> the behavior is not shown at all:

![image](https://cloud.githubusercontent.com/assets/1516470/13955964/12fc4a8c-f047-11e5-9bc1-5fe0ee87aab0.png)

We're not 100% sure when this is the case, in rare cases it seems to work. However, it is very dangerous! The unit test runner shows a "green" state, although assertions failed. In the second scenario it is not even visible that the number of nodes is different to the number of executed tests (see top status bar).

**Comment by bluerobotch** [comment]
I think this is related to #33 too. With what version of ReSharper did you test?

**Comment by drauch** [comment]
Maybe related, however, the effects seem to be different, which is why I reported it in a new issue.

We're using R# 10.0.2 at the moment. Everybody at our site experiences these problems.

**Comment by robertcoltheart** [comment]
Should be fixed, please check.
