### ISSUE TITLE
VS2013 and VS2015 Resharper Ultimate 10.0.2 install error "The path Project Symbols is not a valid file system path"

### ISSUE THREAD

**Issue by Gonzo102** [machine/machine.specifications.runner.resharper#36]
I get an error trying to install this with RS Ultimate 10.0.2.  I have included in log file.
[Jagahew.txt](https://github.com/machine/machine.specifications.runner.resharper/files/204915/Jagahew.txt)

**Comment by Schaeri** [comment]
We have several installations with visual studio 2015 and visual studio 2013. I never saw such an error. Do you have some more details? For example, are you able to install other r# extensions like XUnit.net Test Support for Resharper 10? Do have tried it on clean installation?

**Comment by Gonzo102** [comment]
Go ahead and close this ticket.  It does appear to be a Resharper issue since I was not able to install the Xunit extension either.  Thanks for your reply.

**Comment by Schaeri** [comment]
No problem. I close the issue.

**Comment by Gonzo102** [comment]
Thanks.





Thanks!
Kenneth S. Hines
