### ISSUE TITLE
Error on installing latest version of TestRunner into Resharper 2016.1

### ISSUE THREAD

**Issue by JohnT1** [machine/machine.specifications.runner.resharper#37]
The following error is reported when install the latest runner as a plugin into Resharper 2016.1:

Error resolving type JetBrains.ReSharper.UnitTestFramework.UnitTestPresenterAttribute from assembly <undefined>, request originating from assembly “JetBrains.ReSharper.UnitTestFramework, Version=105.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? False! Is it of our own assembly? False! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False!

Is this Resharper's problem, or the plugin's please?  

Would be very grateful for a fix as I cannot run MSpec tests with the latest version or resharper without this - thanks

**Comment by JohnT1** [comment]
Screenshot from the error
![whoseerror](https://cloud.githubusercontent.com/assets/12639519/14566433/80d52eb4-0327-11e6-828d-2488ad15bd1e.png)

**Comment by Schaeri** [comment]
Currently the runner doesn't support 2016.1. Only r# pre-release. The migration is ongoing and a first version should be online next week.

**Comment by JohnT1** [comment]
Thanks for reply.  Also for planning to update the runner!  We depend on the combination of MSpec / R# in our dev team and want this as an ongoing strategy.

Thanks for MSpec and the plugin....  Great tools

**Comment by JohnT1** [comment]
PS would really appreciate a note on this thread when the new version is issued... as will probably implement it soon after

**Comment by Schaeri** [comment]
Runner released for 2016.1.

**Comment by JohnT1** [comment]
Thanks very much for the fix and for letting me know
