### ISSUE TITLE
Future maintenance of ReSharper runner

### ISSUE THREAD

**Issue by bluerobotch** [machine/machine.specifications.runner.resharper#41]
Over the last 8 months, @schaeri and me contributed to the machine.specifications.runner.resharper project in order to keep it running with the latest version of ReSharper. During this time the ReSharper API changed three times and therefore we released 3 new versions of the runner.

For various reasons our team decided to stop using MSpec and move to an XUnit based approach instead. The main reasons were the unknown future of MSpec itsself and also the pain of adopting the runner to new versions of the poorly documented ReSharper api. Since XUnit is now included in the product, there is no reference implementation anymore. And last but not least, our team wanted to use only one testing framework for unit and specification tests.

For this reason we (@schaeri and @bluerobotch) will no longer maintain the ReSharper runner.
If we could find someone who is willing to maintain the runner i would be happy to provide all information needed to do that.

**Comment by matkoch** [comment]
Everyone who's interested can check out my re-implementation of the MSpec ReSharper runner. It's a complete replacement. Just remove the nuget package from the project, and install `TestFx.MSpec` instead. On ReSharper side, install the [pre-release package](https://resharper-plugins.jetbrains.com/packages/TestFx.ReSharper/0.6.1-Pre00008) from the gallery. I would happily receive some feedback on your existing code base.

**Comment by ivanz** [comment]
Hi,

Me and @einari have taken over the maintenance of MSpec (and GitHub org) and ported the ecosystem to .NET Core (as of 0.11.x releases). I see in #44 that @robertcoltheart has also expressed interest in helping out with the ReSharper plugin. 

Would you be okay with us also potentially looking after this plugin? Would be great to get access to manage [the NuGet package in the JetBrains gallery](https://resharper-plugins.jetbrains.com) - my username there is `ivanz`. I would love to move the CI to AppVeyor and integrate it tightly in GitHub, etc (I have done this for the rest of MSpec already)


/cc @citizenmatt

**Comment by robertcoltheart** [comment]
I'm happy to contribute PRs as needed :smile:

**Comment by bluerobotch** [comment]
Hi @ivanz,

i gave you access to the nuget packages. At the moment the CI is running on a TeamCity server sponsored by [bbv](http://bbv.ch/en/). The Nuget package is directly published from there. As soon as you moved to the new CI let me know, so i can disable the old one.

Btw: thanks for keeping mspec alive :)

**Comment by ivanz** [comment]
Great thanks. I am going on vacation for a 2-3 weeks, so will look at this when I am back, cheers.

**Comment by ivanz** [comment]
@bluerobotch  Can you please turn off the following in TeamCity (I don't have access to TeamCity):

 * machine.specifications.runner.resharper 
 * machine.specifications 
 * machine.fakes 
* machine.specifications.should 

I have moved the ReSharper CI and CD to AppVeyor. It builds on every push and validates pull requests (integrated in GitHub) and deploys from vN.N.N tags to GitHub and ReSharper gallery automatically. Everyone in the machine GitHub org will have access to the machine AppVeyor account I believe.

https://ci.appveyor.com/project/machine-specifications/machine-specifications-runner-resharper

https://ci.appveyor.com/project/machine-specifications/machine-specifications-runner-resharper

**Comment by bluerobotch** [comment]
@ivanz sorry for the delay. I was was on vacation for 5 weeks.

I deleted the builds for: 
* machine.specifications.runner.resharper
* machine.specifications
* machine.specifications.should

There is no build for fakes as i see...

**Comment by ivanz** [comment]
No worries and thanks for this! Hope you had a good break ;)
