### ISSUE TITLE
MSpec tests not detected

### ISSUE THREAD

**Issue by mansichopra** [machine/machine.specifications.runner.resharper#42]
The Resharper Ultimate Extensions (10.0.2) shows listing of available plugins. Installed Machine.Specifications.Runner.Resharper plugin and it showed successful installation. Opening the extensions window after the Visual Studio 2015 restart still shows that the plugin is not installed. Mspec tests are not being detected by ReSharper.

![image](https://cloud.githubusercontent.com/assets/9938389/16216905/989001ac-373c-11e6-923f-36f16631fcff.png)

**Comment by ivanz** [comment]
Does the a newer versions solve this problem for you?

**Comment by ivanz** [comment]
Closing due to no response and unable to reproduce.
