### ISSUE TITLE
Release 1.6.0 with support for ReSharper 2016.2.x

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications.runner.resharper#45]
Release 1.6.0 with support for ReSharper 2016.2.x

**Comment by jorg3ar7uro** [comment]
I am getting this error when I am trying to install this version from Resharper Extensions panel.
“Unable to resolve dependency 'JetBrains.Psi.Features.Cpp.Src (≥ 106.0.20160818.165003)'.”

**Comment by ivanz** [comment]
I am trying to resolve it currently. Stay tuned.

**Comment by ivanz** [comment]
Should be sorted now.
