### ISSUE TITLE
No tests discovered in dotnet cli projects

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications.runner.resharper#46]
No tests are discovered with 1.6.0-beta5 with ReSharper 2016.2.2 in dotnet cli projects

**Comment by citizenmatt** [comment]
ReSharper 2016.2 doesn't currently support .net core tests. It's supported in 2016.3 which is just about to start EAP. Annoyingly, it's another recompile (we're looking at making life less painful with recompiling plugins, I feel it lots too) and another interface to implement.

The high level view is that ReSharper will continue to discover tests in the editor, and then call `dotnet test` whenever you build. It requires a new interface to match these discovered tests to the unit test elements from the editor, and then everything else should just work as before.

More details once we announce the EAP opening, which will be _very, very soon_. As in, if you know where to look...

**Comment by ivanz** [comment]
Thanks for the update. When you say that ReSharper will "continue to discover tests in the editor" and then call "dotnet test" - does that imply that it's not going to rely on the [dotnet test communication protocol](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/test-protocol) implemented by the dotnet test runners?

**Comment by citizenmatt** [comment]
Nope, it's using the protocol. But the protocol doesn't give us the rich support we're used to from the as-you-type discovery. So we still do that.

We use `dotnet test` to be the source of truth for the tests we run, rather than rely on our in-source discovery. We know this will give us an accurate list of tests. (We do the same with desktop CLR - scanning the compiled assembly when you build).

And we've just announced the EAP: https://blog.jetbrains.com/dotnet/2016/09/23/resharper-ultimate-2016-3-eap-opens/

The EAP SDK is also available on nuget. I'm aiming to write up the new interface in the devguide on Monday.

**Comment by ivanz** [comment]
Ok cool - I will wait for the guide. I haven't implemented yet the protocol in the dotnet test mspec runner :)

**Comment by citizenmatt** [comment]
Ah, I didn't know how far along support was :)

**Comment by citizenmatt** [comment]
I've written up [how to support .net core tests in ReSharper](https://www.jetbrains.com/help/resharper/sdk/Features/UnitTest/DotNetCore.html). Let me know if it makes sense, or could be improved.

**Comment by citizenmatt** [comment]
Hi all. What's the status of this, and the [dotnet-test-mspec](https://github.com/machine/dotnet-test-mspec) project?

We've been asked about support for .net core mspec tests on Linux in Rider ([RIDER-3445](https://youtrack.jetbrains.com/issue/RIDER-3445)), which could be solved by this plugin being updated to support .net core. So I was wondering how far along dotnet-test-mspec is, and what's happening with the ReSharper plugin.

But to complicate matters, .net core testing is changing, with the changes introduced by VS2017RC and the move to .csproj and msbuild. The existing `dotnet-test-xunit` route no longer works. I don't have any more information right now. I'm trying to find out more.

**Comment by ivanz** [comment]
Hey, thanks for the write up! I am waiting on things to stabilise in .NET Core tooling land before spending time on this... Seems a lot is in flux still

**Comment by ivanz** [comment]
@citizenmatt What's the latest on this? Are you building on top of the new vstest stuff or?

**Comment by matkoch** [comment]
@ivanz for .NET Core projects (project with the new format) you will need to implement `DotNetVsTestArtefactExplorer` to discover tests properly. By having a reference to the ReSharper SDK, you should be able to explore `XunitDotNetVsTestArtefactExplorer` as an example implementation.

**Comment by matkoch** [comment]
https://www.jetbrains.com/help/resharper/sdk/Features/UnitTest/DotNetCore.html

**Comment by derekgreer** [comment]
Is there any update on this?

**Comment by robertcoltheart** [comment]
I'm working hard on this. I don't have an ETA for you though.

**Comment by robertcoltheart** [comment]
I'm having issues testing this with VS 15.3 and R#, as documented here: https://youtrack.jetbrains.com/issue/RSRP-464926. Will try again with EAP or wait until 2017.2 is released.

**Comment by lundmikkel** [comment]
@robertcoltheart I'm using R# 2017.2 and the 2.0.0-beta.2 runner, but I'm still not able to see any of the MSpec tests in my net461 core project. The description for the beta release says "prep work for supporting dotnet core," but what is the actual status? I would hate having to use the VS test runner :(

**Comment by robertcoltheart** [comment]
Yep, still a WIP I'm afraid. Working as hard as I can to get this done ASAP. My free time is severely limited 😢

**Comment by robertcoltheart** [comment]
@citizenmatt I might need some help here. I've implemented the dotnet core interfaces etc as per the SDK documentation. However when I refresh the tests in the Unit Test Explorer, the tests all disappear, despite the element mapper firing correctly and creating the `IUnitTestElement` objects.

Any hints?

**Comment by citizenmatt** [comment]
Are you creating new elements or finding existing ones? It should be reusing the elements that you've already found in the editor.

**Comment by robertcoltheart** [comment]
Returning existing elements. Still the same issue. Nevermind, I'll go through the Xunit provider in detail and see what I'm missing. I'm sure it's something simple.

**Comment by robertcoltheart** [comment]
Ok, not so simple. I've stripped the code down to the basics, and copy+pasted almost everything from the Xunit provider - still the same issue: all the tests disappear from the explorer window when you refresh, and the tests are not runnable via the R# gutter icons. I'm starting to think the issue lies within the `Machine.TestAdapter` code? @citizenmatt Do you have any tips for debugging the VS runner that is returned via `IDotNetVsTestBasedUnitTestProvider.GetExtensionName`? Specifically in conjunction with a R# unit test provider like this.

**Comment by citizenmatt** [comment]
Have you looked at the log in ReSharper's test runner window? Click the "OK" or "ERROR" in the top right, and you'll be shown a log. You can right click it to change the log level of what's shown.

You can also run in Internal mode - `devenv.exe /ReSharper.Internal`. Now on the Unit Testing options page are two options, one of which is logging. This will write to `%TEMP%\JetLogs`, IIRC. Hopefully this should be enough to see what's happening.

The `IDotNetVsTestBasedUnitTestProvider.GetExtensionName` is the name of the test adapter assembly for the `dotnet test` process. For MSTest and Xunit, it's one of their assemblies. I presume you have an adapter, too? Is this `Machine.TestAdapter`?

**Comment by robertcoltheart** [comment]
Correct, we have `Machine.TestAdapter` which is doing the test discovery from dotnet. I'll try the above options and see if I get anything useful, thanks.

**Comment by robertcoltheart** [comment]
Ok, got something here @citizenmatt, any help deciphering?

```
Transition failed: Transition from state <v1.Discovery> on event <remote::1.TestDiscovery.Completed>. Cause: System.InvalidCastException: Unable to cast object of type 'JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.v1.TestCase' to type 'JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetTest.v1.Payloads.Test'. at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetTest.DotNetTestCaseMap.Register(IUnitTestElement element, Object testCase) at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.CreateElements(TestCase testCase) at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.TestsDiscovered(TestCase[] tests) at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.OnDiscoveryComplete(DiscoveryCompletePayload payload) at Appccelerate.StateMachine.Machine.ActionHolders.ArgumentActionHolder`1.Execute(Object argument) at Appccelerate.StateMachine.Machine.Transitions.Transition`2.PerformActions(ITransitionContext`2 context)

--- EXCEPTION #1/1 [LoggerException]
Message = “
  Transition failed: Transition from state <v1.Discovery> on event <remote::1.TestDiscovery.Completed>.
  Cause: System.InvalidCastException: Unable to cast object of type 'JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.v1.TestCase' to type 'JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetTest.v1.Payloads.Test'.
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetTest.DotNetTestCaseMap.Register(IUnitTestElement element, Object testCase)
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.CreateElements(TestCase testCase)
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.TestsDiscovered(TestCase[] tests)
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.OnDiscoveryComplete(DiscoveryCompletePayload payload)
     at Appccelerate.StateMachine.Machine.ActionHolders.ArgumentActionHolder`1.Execute(Object argument)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.PerformActions(ITransitionContext`2 context)
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
Data.SccRevisionShell = “<there are no packages matching the criteria>”
Data.HostProductInfo = “JetBrains ReSharper Ultimate 2017.2  Build 109.0.20170824.131346”
Data.SubProducts.#0 = “JetBrains ReSharper 2017.2 Build 2017.2.20170824.133358”
Data.SccRevisionEnv = “
  Platform\Core\Shell:
  	git::refs/heads/wave09-eap14-rtm::951d670da4a89a473f82e824e075d61fee8aa327
  
  
  Platform\VisualStudio:
  	git::refs/heads/wave09-eap14-rtm
”
Data.VsVersion = 15.3.26730.15
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestProtocol.<.ctor>b__e(Object sender, TransitionExceptionEventArgs`2 args)
     at Appccelerate.StateMachine.Machine.StateMachine`2.RaiseEvent[T](EventHandler`1 eventHandler, T arguments, ITransitionContext`2 context, Boolean raiseEventOnException)
     at Appccelerate.StateMachine.Machine.StateMachine`2.OnExceptionThrown(ITransitionContext`2 context, Exception exception)
     at Appccelerate.StateMachine.Machine.Contexts.TransitionContext`2.OnExceptionThrown(Exception exception)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.HandleException(Exception exception, ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.PerformActions(ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.Fire(IState`2 source, IState`2 target, ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.Fire(IState`2 source, IState`2 target, ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.Fire(IState`2 source, IState`2 target, ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.Transitions.Transition`2.Fire(ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.States.State`2.Fire(ITransitionContext`2 context)
     at Appccelerate.StateMachine.Machine.StateMachine`2.Fire(TEvent eventId, Object eventArgument)
     at Appccelerate.StateMachine.PassiveStateMachine`2.ProcessQueuedEvents()
     at Appccelerate.StateMachine.PassiveStateMachine`2.Execute()
     at Appccelerate.StateMachine.PassiveStateMachine`2.Fire(TEvent eventId, Object eventArgument)
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.Channel.DotNetCoreMessageListener.<>c__DisplayClass2`1.<RegisterMessage>b__1(JToken payload)
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.Channel.DotNetCoreMessageListener.OnMessage(String rawMessage)
     at JetBrains.ReSharper.UnitTestFramework.DotNetCore.Channel.DotNetCoreRemoteChannel.ReaderThreadProc()
     at JetBrains.ReSharper.TaskRunnerFramework.RemoteChannelBase.<Start>b__0(Object _)
     at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
”

```

**Comment by robertcoltheart** [comment]
Ugh, figured it out. @citizenmatt for future reference, here is the issue:

`DotNetVsTestArtefactExplorer<>` and `DotNetTestArtefactExplorer<>` both take `IDotNetCoreTestCaseMap` as a constructor parameter, which is what you get if you take R#'s word for it when generating the constructor. No hints there.

What they actually expect, however, is `IDotNetTestCaseMap` (for `DotNetTestArtefactExplorer<>`) and `IDotNetVsTestCaseMap` (for `DotNetVsTestArtefactExplorer<>`) respectively. Not mentioned anywhere in the SDK docs or constrained by the base constructors 😡. (Hint: maybe the API should be changed here? Or better handle the cast in the `Register` method?)

Gimme back the 14 hours I lost on this...

At least I'm back on track again!

**Comment by ivanz** [comment]
@robertcoltheart On behalf of all MSpec and ReSharper users I want to say *HUGE* thanks for investing your time and effort into this and thank you again for your perseverance!

**Comment by matkoch** [comment]
Following to say thanks. Implementing support for test frameworks has always been a very hard challenge. The problem with documentation is that MSpec seems to be the only major framework that is maintained externally. So the benefit of keeping this up-to-date is much lower. Anyways, thanks again. I hope this was a one-time adventure with .NET Core :)

**Comment by robertcoltheart** [comment]
@ivanz How do you feel about some changes in the `Machine.Specifications` library? The dotnet core mapper doesn't get enough information from the test adapter regarding behaviors and behavior specs. Specifically the field name in the context (ie. the `behaves_like` field name). I'm still exploring whether I can do what I need with what I have (ie using reflection or something else), or whether I need to raise a PR.

**Comment by citizenmatt** [comment]
Well done @robertcoltheart! I'll pass this feedback on to the dev team. Thanks!

**Comment by ivanz** [comment]
> @ivanz How do you feel about some changes in the Machine.Specifications library? The dotnet core mapper doesn't get enough information from the test adapter (from AssemblyExplorer) regarding behaviors and behavior specs. Specifically the field name in the context (ie. the behaves_like field name). I'm still exploring whether I can do what I need with what I have (ie using reflection or something else), or whether I need to raise a PR.

If you check if the `Specification` is of type `BehaviorSpecification` (https://github.com/machine/machine.specifications/blob/master/Source/Machine.Specifications/Model/BehaviorSpecification.cs / https://github.com/machine/machine.specifications/blob/d30c41f23973f9a0064e874b26a170fe3984863a/Source/Machine.Specifications/Factories/SpecificationFactory.cs#L28) - does that help a bit?

Agreed - the interface exposed for running Behaviors is sub-optimal at the moment in MSpec. You can see some ugly hacks that the Test Adapter has to do:
* https://github.com/machine/machine.vstestadapter/blob/129f1d610c8aca9234c3973fbfc2991029b6b513/Source/Machine.VSTestAdapter/Execution/TestExecutor.cs#L78

**Comment by robertcoltheart** [comment]
Thanks, that helps a bit, but it still doesn't expose the `behaves_like` field name. I'll see whether I can get around this, else just raise a PR with a change.

**Comment by robertcoltheart** [comment]
Just as a quick update, this issue is currently block by a pending change in `machine.specifications` and then by a change in `machine.vstestadapter`. The rest of the work for `dotnet core` is complete.

**Comment by lundmikkel** [comment]
@robertcoltheart Amazing job! So glad to see version 2 support .NET Core. Thanks for a great effort! Looking forward to using it.

**Comment by derekgreer** [comment]
What version was this tested with?  I've got Resharper 2017.2.2 installed with the following references, but not it isn't picking up the tests:

  <ItemGroup>
    <PackageReference Include="Machine.Specifications" Version="0.12.0" />
    <PackageReference Include="Machine.Specifications.Runner.VisualStudio" Version="2.5.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
  </ItemGroup>

**Comment by robertcoltheart** [comment]
@derekgreer This is tested against 2017.2.2, as you mentioned. Make sure you have referenced the following packages:

- Machine.Specifications (0.12.0)
- Machine.Specifications.Runner.VisualStudio (2.5.1)
- Microsoft.NET.Test.Sdk (any version I think)

Let me know if you can't get it working, or attached a sample project with your specific case.

**Comment by derekgreer** [comment]
I didn't notice, but the references I included in the previous comment must have gotten filtered out because I pasted in HTML.

Here is what I have:

```
<ItemGroup>                                                                                           
    <PackageReference Include="Machine.Specifications" Version="0.12.0" />                              
    <PackageReference Include="Machine.Specifications.Runner.VisualStudio" Version="2.5.1" />     
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
  </ItemGroup>                                                                                          
```

I'll test with a new project I can share to see if it works.

**Comment by derekgreer** [comment]
[TestResharperMspec..20171016-1508160610.zip](https://github.com/machine/machine.specifications.runner.resharper/files/1387585/TestResharperMspec.20171016-1508160610.zip)

**Comment by robertcoltheart** [comment]
Has to be something in your setup, all seems fine to me.

VS 15.4.0
R# 2017.2.2

![image](https://user-images.githubusercontent.com/13191652/31633210-396e31f2-b2f2-11e7-8f98-fb8d50ef23ac.png)

**Comment by ivanz** [comment]
Can confirm as well that it works here. I had to install VS & Resharper from scratch and 15.4.0 with latest R# with the MSpec extension installed version 2.0.0 everything works 🎉

**Comment by derekgreer** [comment]
I was able to get it working.  Thanks!

**Comment by derekgreer** [comment]
Okay, so it kind of works for me.  If I explicitly run a test then it works, but `Resharper -> Unit Tests -> Run All Tests from Solution` only picks up tests from currently opened files.  

@robertcoltheart Does run all tests in solution work for you?
