### ISSUE TITLE
Resharper 2016.3 no runner

### ISSUE THREAD

**Issue by Cesar-Ofi** [machine/machine.specifications.runner.resharper#49]
I have upgraded to new Resharper 2016.3 and now I don´t have mspec runner integrated with VS 2015.

I can´t find runner in extensions installed. Also, if I try to find in extensions manager, even with pre-release enabled, mspec runner doesn´t appears

Is this project discontinued?

**Comment by agross** [comment]
See https://github.com/machine/machine.specifications.runner.resharper/pull/48
