### ISSUE TITLE
Support for ReSharper 2017.1

### ISSUE THREAD

**Issue by bryancrosby** [machine/machine.specifications.runner.resharper#52]
Any plans to support Resharper 2017.1 or what effort it might take?

**Comment by ivanz** [comment]
Just released version 1.8 of the plugin and it should show up in the extensions list shortly. In general upgrades involve updating all the JetBrains SDK packages and making adjustments for any breaking changes. In this case it was fairly smooth.

**Comment by bryancrosby** [comment]
Thanks for the quick response!
