### ISSUE TITLE
No Tests Found for Resharper 2017.1, Machine.Specifications.Runner.Resharper for Resharper 2017.1, netcoreapp1.1 project

### ISSUE THREAD

**Issue by derekgreer** [machine/machine.specifications.runner.resharper#55]
For a .Net Framework 4.5.2 based project the MSpec VS integration works, but when I create a core project it doesn't.

**Comment by ryudice** [comment]
Same issue here

**Comment by ivanz** [comment]
This is a dupe of #46 - I am not really sure what's the latest bits that need to be implemented for the runner to support ReSharper's .NET Core support - things have been in flux a lot over the last months.
