### ISSUE TITLE
IAssemblyContext is ignored by the ReSharper Runner

### ISSUE THREAD

**Issue by DerAlbertCom** [machine/machine.specifications.runner.resharper#7]
If a Specs Assembly use IAssemblyContext, it will not be used.

**Comment by agross** [comment]
I cannot confirm with 1.0.0. Is the `IAssembyContext` `public`?

**Comment by DerAlbertCom** [comment]
A little Repro. 

```csharp
using Machine.Specifications;

namespace SampleSpecs
{
    public class TheContext : IAssemblyContext
    {
        static private string foo;

        public static string Foo
        {
            get { return foo; }
        }

        public void OnAssemblyStart()
        {
            foo = "ok";
        }

        public void OnAssemblyComplete()
        {
        }
    }

    [Subject(typeof(TheContext))]
    public class When_a_spec_in_running
    {
        private Establish context = () => { };

        private It should_run = () => TheContext.Foo.ShouldEqual("ok");
    }
}

```

**Comment by agross** [comment]
This works for me. Can you post a reproduction project?

**Comment by DerAlbertCom** [comment]
File New Project ;) VS 2013 Update 4, ReSharper 9.0 Update 1, Machine Specifications.Runner.Resharper9 build 1.0.0 

Download SampleSpecs => https://onedrive.live.com/redir?resid=D491B36AC797CD65%21136006

Runs in NCrunch, does not work in ReSharper

![bildschirmfoto 2015-01-16 um 19 52 10](https://cloud.githubusercontent.com/assets/136992/5782281/1497e7b0-9dba-11e4-959d-cbc0bcf7e1ae.png)


JetBrains ReSharper Platform 6 Build 6.0.20141219.120158 on 2014-12-19 12:56:02Z
JetBrains dotCover 3.0 Update 1 Build 3.0.20141219.140120 on 2014-12-19 14:04:16Z
JetBrains dotMemory 4.2 Update 1 Build 4.2.20141219.130159 on 2014-12-19 13:21:38Z
JetBrains dotTrace 6.0 Update 1 Build 6.0.20141219.130145 on 2014-12-19 13:21:24Z
JetBrains ReSharper 9.0 Update 1 Build 9.0.20141219.130142 on 2014-12-19 13:12:31Z
JetBrains TeamCity Add-in 9.0 Update 1 Build 9.0.20141219.130134 on 2014-12-19 13:13:21Z

Application Packages:
EtherealCode ReSpellerPro build 3.1.0.0 on 2015-01-10 15:14:25Z.
JetBrains DotCommon Core build 1.0.20141219.120183 on 2014-12-19 12:59:24Z.
JetBrains DotCommon.Psi Navigation build 3.0.20141219.130131 on 2014-12-19 13:13:19Z.
JetBrains DotCommon.Psi UnitTesting build 3.0.20141219.130131 on 2014-12-19 13:13:19Z.
JetBrains DotCommon Remotable build 1.0.20141219.120183 on 2014-12-19 12:59:24Z.
JetBrains DotCommon Timeline build 1.0.20141219.120183 on 2014-12-19 12:59:24Z.
JetBrains DotCover Core build 3.0.20141219.140120 on 2014-12-19 14:04:16Z.
JetBrains DotCover Presentation build 3.0.20141219.140120 on 2014-12-19 14:04:16Z.
JetBrains DotCover VisualStudio build 3.0.20141219.140120 on 2014-12-19 14:04:16Z.
JetBrains DotMemory Common build 4.2.20141219.130159 on 2014-12-19 13:21:38Z.
JetBrains DotMemory VisualStudio build 4.2.20141219.130159 on 2014-12-19 13:21:38Z.
JetBrains DotTrace Core build 6.0.20141219.130145 on 2014-12-19 13:21:24Z.
JetBrains DotTrace VisualStudio build 6.0.20141219.130145 on 2014-12-19 13:21:24Z.
JetBrains EtwService Core build 1.0.20141219.120210 on 2014-12-19 12:59:51Z.
JetBrains EtwService msi build 1.0.20141219.120193 on 2014-12-19 12:55:38Z.
JetBrains EtwService Native Core build 1.1.20141219.120193 on 2014-12-19 12:55:38Z.
JetBrains Fake VisualStudio VsPackageAssembly build 12.0.0.0 on 2015-01-10 15:14:58Z.
JetBrains Platform Core Ide build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Core Shell build 6.0.20141219.120162 on 2014-12-19 12:53:09Z.
JetBrains Platform Core Text build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Installer build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Standalone Shell build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Symbols build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform VisualStudio build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Profiler Configurator Core build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Configurator WPF build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Editor Core build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Editor Windows BehaviorModel build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Editor Windows WPF build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Kernel CleanUp build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Kernel Core build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Kernel InternalLauncher build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Kernel Windows Api build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Kernel Windows Engine build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler Kernel Windows Native Core build 1.0.20141219.120210 on 2014-12-19 12:55:55Z.
JetBrains Profiler Snapshot build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler VsIntegration Core build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Profiler VsIntegration Windows build 1.0.20141219.130143 on 2014-12-19 13:01:42Z.
JetBrains Psi.Features ExternalAnnotations build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features SolutionBuilder build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features src build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features Tasks build 6.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features TeamCity src build 9.0.20141219.130134 on 2014-12-19 13:13:21Z.
JetBrains Psi.Features VisualStudio build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains ReSharper src build 9.0.20141219.130142 on 2014-12-19 13:12:31Z.
Machine Specifications.Runner.Resharper9 build 1.0.0 on 2015-01-10 15:14:25Z.
ReSharper DictionaryHelper.90 build 0.6.4 on 2015-01-10 15:14:25Z.
ReSharper InternalsVisibleTo.R90 build 0.1.5 on 2015-01-10 15:14:27Z.
ReSharper Postfix.R90 build 2.0.9 on 2015-01-10 15:14:25Z.

dotCover 3.0.1.0 Licensed to Albert Weinert. Maintenance subscription until 24.07.2015
ReSharper 9.0.0.0 Licensed to Albert Weinert. Maintenance subscription until 24.07.2015
Visual Studio 12.0.31101.0.

Copyright © 2015 JetBrains. All rights reserved.

**Comment by agross** [comment]
Still green. I don't have dotCover installed (only ReSharper), perhaps this causes the issue?

```
JetBrains ReSharper Platform 6 Build 6.0.20141219.120158 on 2014-12-19 12:56:02Z
JetBrains ReSharper 9.0 Update 1 Build 9.0.20141219.130142 on 2014-12-19 13:12:31Z

Application Packages:
CitizenMatt Xunit build 2.0.1 on 2015-01-16 17:43:28Z.
JetBrains Fake VisualStudio VsPackageAssembly build 12.0.0.0 on 2015-01-16 17:43:43Z.
JetBrains NuPeek build 1.3 on 2015-01-16 17:43:28Z.
JetBrains Platform Core Ide build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Core Shell build 6.0.20141219.120162 on 2014-12-19 12:53:09Z.
JetBrains Platform Core Text build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Installer build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Symbols build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform VisualStudio build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Psi.Features ExternalAnnotations build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features SolutionBuilder build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features src build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features Tasks build 6.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features VisualStudio build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains ReSharper src build 9.0.20141219.130142 on 2014-12-19 13:12:31Z.
Machine Specifications.Runner.Resharper9 build 1.0.0 on 2015-01-16 17:43:28Z.
ReSharper DictionaryHelper.90 build 0.6.4 on 2015-01-16 17:43:28Z.
ReSharper InternalsVisibleTo.R90 build 0.1.5 on 2015-01-16 17:43:28Z.
ReSharper Postfix.R90 build 2.0.9 on 2015-01-16 17:43:28Z.
ReSharper ReJS.R90 build 0.5.5 on 2015-01-16 17:43:28Z.
Resharper TestCop.R9 build 1.9.0.1 on 2015-01-16 17:43:29Z.

ReSharper 9.0.0.0 Licensed to Alexander Gross. Maintenance subscription until 22.07.2015
Visual Studio 12.0.31101.0.

Copyright © 2015 JetBrains. All rights reserved.
```

**Comment by DerAlbertCom** [comment]
I removed dotCover and dotTrace ... still red. What next?

**Comment by agross** [comment]
Try an experimental hive in VS with ReSharper only and no other extensions. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by DerAlbertCom** [comment]
Fresh installed Visual Studio 2015 CTP 5 in a new Windows 10 Preview 2 VM. Only Firefox installed.
Still don't work.

**Comment by DerAlbertCom** [comment]
JetBrains ReSharper Platform 6 Build 6.0.20141219.120158 on 2014-12-19 12:56:02Z
JetBrains ReSharper 9.0 Update 1 Build 9.0.20141219.130142 on 2014-12-19 13:12:31Z

Application Packages:
JetBrains Fake VisualStudio VsPackageAssembly build 14.0.0.0 on 2015-01-24 20:14:42Z.
JetBrains Platform Core Ide build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Core Shell build 6.0.20141219.120162 on 2014-12-19 12:53:09Z.
JetBrains Platform Core Text build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Installer build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Symbols build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform VisualStudio build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Psi.Features ExternalAnnotations build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features SolutionBuilder build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features src build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features Tasks build 6.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains Psi.Features VisualStudio build 9.0.20141219.130140 on 2014-12-19 13:00:40Z.
JetBrains ReSharper src build 9.0.20141219.130142 on 2014-12-19 13:12:31Z.
Machine Specifications.Runner.Resharper9 build 1.0.0 on 2015-01-24 20:14:25Z.

ReSharper 9.0.0.0 Free trial period is running. 30 days left
Visual Studio 14.0.22512.0.

Copyright © 2015 JetBrains. All rights reserved.

**Comment by danielmarbach** [comment]
Really strange! They are executed by the core and not resharper. Are your implementations somehow special?

**Comment by DerAlbertCom** [comment]
Which implemtations... a very simple test case is attached to the issue.

**Comment by Cantaria** [comment]
same problem with ReSharper 9.

Disable Shadow-Copy helped for me:

![resharper and unit test fun](https://cloud.githubusercontent.com/assets/7793709/6001207/356bfb7c-aae7-11e4-8163-d43f6273b13a.png)

**Comment by DerAlbertCom** [comment]
Can confirm this, with disabled Shadow-copy of the assemblies it works.
