### ISSUE TITLE
`Run all test` doesn't work properly

### ISSUE THREAD

**Issue by MNie** [machine/machine.specifications.runner.resharper#73]
Visual Studio 15.4.4
Resharper 2017.2.2
new format of csproj

Steps to reproduce:
1. Build project with multiple test classes inside
2. Click 'Run Unit Tests' on project
3. Runner discover and run tests only from a currently open file
4. Open another file which contains tests -> more tests were discovered
5. Open another one file which contains tests -> even more tests were discovered.

I think it could be related to #71 
In my opinion runner should behave in the same way as it behaves with old format of csproj (no need to open every file to discover specs).
The question is, is it related to Machine.Specifications runner or Resharper?

CC: @robertcoltheart @citizenmatt

**Comment by MNie** [comment]
@robertcoltheart any update :)?

**Comment by robertcoltheart** [comment]
Apologies, life has gotten in the way. I hope to get to this over the holiday season.

**Comment by MNie** [comment]
@robertcoltheart ok, thanks! :)

**Comment by MNie** [comment]
@robertcoltheart  FYI problem still occurs in MachineSpecifications.Runner ver 2.1.0

**Comment by robertcoltheart** [comment]
Noted thanks

**Comment by robertcoltheart** [comment]
Can you do me a favour and try creating a similar project but using Xunit, and seeing whether the same problem exists? I can replicate this issue with *both* Mspec and Xunit, which seems to suggest this is an issue with R# itself. I followed these steps:

1. Open test solution and run "Clean Solution", make sure all file editors are closed
2. Clear all the R# caches from ReSharper->Options->General->Clear caches
3. Close VS
4. Re-open VS and open the test solution
5. Do not see any tests in the "Unit Test Explorer" window even after some time
6. Open a file, now the test appears in the unit test explorer

My guess is that R# uses the `dotnet cli` to discover the tests, and this can't be done before the project is built?

@citizenmatt?

**Comment by MNie** [comment]
@robertcoltheart of course I will do that later today and give you feedback.

**Comment by MNie** [comment]
@robertcoltheart I confirm, for xunit it also doesn't work.

**Comment by robertcoltheart** [comment]
I'm gonna close this, and I'd suggest raising an issue over on YouTrack for R# for this issue.

**Comment by MNie** [comment]
@robertcoltheart Issue raised on [R# YouTrack](https://youtrack.jetbrains.com/issue/RSRP-467721)
