### ISSUE TITLE
No console output in test runner

### ISSUE THREAD

**Issue by MattRyan** [machine/machine.specifications.runner.resharper#78]
I no longer receive any console output when running tests. I have updated to ReSharper version 2017.3.2 and test runner version 2.1.2.

Additionally I receive the following warning in the execution log.
`2018.02.14 22:14:15.683    WARN Run: 6556ebe8-a7e4-4db1-af84-3275837d3910 - Cannot find element for task <a1c08f36-bbd9-4772-809b-773b749ba87e> of type <MspecTestAssemblyTask>`

**Comment by MattRyan** [comment]
After reviewing the code it appears that problem is in the TestRunListener. OnSpecificationEnd method writes the captured output of the specification but no similar logic exists for OnContextEnd.

**OnSpecificationEnd**
`public void OnSpecificationEnd(SpecificationInfo specificationInfo, Result result)
{
    var task = _context.GetBehaviorTask(_currentContext, specificationInfo) ??
               _context.GetSpecificationTask(specificationInfo);

    if (task == null)
        return;

    Output(task, specificationInfo.CapturedOutput);

    if (result.Status == Status.Failing)
    {
        _errors++;
        _server.TaskException(task, GetExceptions(result.Exception));
        _server.TaskFinished(task, GetExceptionMessage(result.Exception), TaskResult.Exception);
    }
    else if (result.Status == Status.Passing)
    {
        _successes++;
        _server.TaskFinished(task, string.Empty, TaskResult.Success);
    }
    else if (result.Status == Status.NotImplemented)
    {
        Output(task, "Not implemented");
        _server.TaskFinished(task, "Not implemented", TaskResult.Inconclusive);
    }
    else if (result.Status == Status.Ignored)
    {
        Output(task, "Ignored");
        _server.TaskFinished(task, string.Empty, TaskResult.Skipped);
    }
}`

**OnContextEnd**
`public void OnContextEnd(ContextInfo contextInfo)
{
    var result = TaskResult.Inconclusive;

    if (_errors > 0)
        result = TaskResult.Error;
    else if (_specifications == _successes)
        result = TaskResult.Success;

    var task = _context.GetContextTask(contextInfo);
    var message = result == TaskResult.Error ? "One or more tests failed" : string.Empty;

    if (task != null)
        _server.TaskFinished(task, message, result);
}`

**Comment by MattRyan** [comment]
Opened a pull request with the proposed changes. #79

**Comment by robertcoltheart** [comment]
I've merged your PR and released it. Let me know if this solves your issue.

**Comment by MattRyan** [comment]
Issue is resolved with latest update. I am still getting the warning in the log but will move that to a separate issue.
