### ISSUE TITLE
Warning in ReSharper test execution log

### ISSUE THREAD

**Issue by MattRyan** [machine/machine.specifications.runner.resharper#83]
The following warning appears in the execution log whenever I run a test. The GUIDs change for each run but are never the same.
`2018.02.14 22:14:15.683 WARN Run: 6556ebe8-a7e4-4db1-af84-3275837d3910 - Cannot find element for task <a1c08f36-bbd9-4772-809b-773b749ba87e> of type <MspecTestAssemblyTask>`

**Comment by robertcoltheart** [comment]
Do you have a demo app you can attach to this issue to help us reproduce?

**Comment by MattRyan** [comment]
I am no longer seeing this issue on the latest version.
